### ISSUE TITLE
Почему в коде нет функции GetClassObject ?

### ISSUE THREAD

**Issue by tormozit** [Infactum/addin-template#10]
Тут пишут что функция должна быть
https://infostart.ru/public/184119/
https://its.1c.ru/db/metod8dev#content:3221:hdoc

**Comment by Infactum** [comment]
Что значит нету?

https://github.com/Infactum/addin-template/blob/bba636a656ebd68cf060d1eaf65c7d2b1802631b/include/ComponentBase.h#L233

https://github.com/Infactum/addin-template/blob/bba636a656ebd68cf060d1eaf65c7d2b1802631b/src/exports.cpp#L35-L44

**Comment by tormozit** [comment]
Виноват. Плохо искал. Спасибо.
