### ISSUE TITLE
Не получается подключить внешнюю библиотеку для работы с оборудованием

### ISSUE THREAD

**Issue by dazdraby** [Infactum/addin-template#11]
Есть внешняя библиотека для работы с оборудованием. Добавляю новое свойство и метод, который вызывает функции из внешней либы. Добавил следующие настройки cmake:
```
set(INC_LIB_DIR p:/Git/1CComponent/zkfvapi/include)
set(LINK_LIB_DIR p:/Git/1CComponent/zkfvapi/x86lib)
include_directories(${INC_LIB_DIR})
link_directories(${LINK_LIB_DIR})
link_libraries(zkfvapi)

```
Все прекрасно собирается и линкуется, без ошибок, но внешняя компонента перестает подключаться в 1С.

**Comment by Infactum** [comment]
Вины шаблона тут практически точно нет.
Линкуете наверное с динамической библиотекой, которую платформа не может найти в момент попытки загрузку компоненты? Хотя бы ТЖ посмотреть стоит.
Если уверены, что DLL загружается - смотрите отладчиком.

**Comment by dazdraby** [comment]
Библиотека статическая. Всё перестает работать, когда есть обращение к функциям внешней либы, все остальное работает. Скорее всего проблема в настройках cmake... По ТЖ не сообразил. Посмотрю. Спасибо.

**Comment by dazdraby** [comment]
Вы были правы... Линковалась статическая либа, но в ней были зависимости от внешних dll. Выяснил с помощью DependencyWalker. Все заработало. Огромное спасибо за вашу компоненту!
