### ISSUE TITLE
Использование gRPC и Protobuf в компоненте

### ISSUE THREAD

**Issue by TimurDD** [Infactum/addin-template#18]
Уже который день бьюсь с ++, SDK и пр... Пытаюсь затащить в библиотеку gRPC и Protobuf, но ни как не получается (при чем года полтора было норм). При вызове метода в 1С ПодключитьВнешнююКомпоненту возвращает ложь. Делал полный тех журнал... Особо интересной инфы там нет.
Как делаю:
Сделал отдельный класс (ToolsAPI1C), который реализует логику работы компоненты. В основном классе указатель (умный) на класс реализации.

Основной класс:
'class TinkoffAPI final : public Component {
public:
    const char *Version = u8"1.0.0";

    TinkoffAPI();
    ~TinkoffAPI();

private:
    string extensionName() override;

    std::shared_ptr<ToolsAPI1C> api;

    // Методы компоненты
    void Init(const variant_t &host, const variant_t &token);
    void pause(const variant_t &delay);
};
'

В конструкторе инициализирую объект:
'
api = std::make_shared<ToolsAPI1C>();`

Вызов из основного класса:
void TinkoffAPI::Init(const variant_t &host, const variant_t &token)
{
    api->Init(std::get<string>(host), std::get<string>(token));
}
'

Класс ToolsAPI:
'
class ToolsAPI1C
{
private:
    'std::shared_ptr<InvestApiClient> m_client;'
public:
    ToolsAPI1C();
    ~ToolsAPI1C();

    // Методы компоненты
    void Init(const string &host, const string &token);
    void pause(const int32_t &delay);
};
'

И реализация:
'
ToolsAPI1C::ToolsAPI1C()
{
}

ToolsAPI1C::~ToolsAPI1C()
{
}

void ToolsAPI1C::Init(const string &host, const string &token)
{
    m_client = std::make_shared<InvestApiClient>(host, token);
}

void ToolsAPI1C::pause(const int32_t &delay)
{
    this_thread::sleep_for(std::chrono::seconds(delay));
}
'

Если убрать (закомментить) m_client = std::make_shared<InvestApiClient>(host, token);, то все работает. Компонента подключается, +вызов метода pause тоже работает корректно. Но стоить разкоментить..

Подскажите, куда копать, библиотека собирается без ошибок. Пробовал играться с типом библиотек (вспомогательные) ставить SHARED, STATIC по  всякому. Результат один(

**Comment by TimurDD** [comment]
Почему то код в ишузе не весь отображается, например std::shared_ptr<InvestApiClient> m_client;

**Comment by TimurDD** [comment]
Чтот гитхат не отображает, что указано в <>, но там классы указаны верно, иначе не собиралось библиотека

**Comment by Infactum** [comment]
> ПодключитьВнешнююКомпоненту возвращает ложь

Скорее всего библиотеку с компонентой не удалось загрузить. Может классический случай с отсутствием необходимых зависимостей, которые приехали с gRPC и тем, что еще у вас там есть.
В любом случае непосредственно к шаблону это отношения не имеет.

Вот такой чат в телеге по компонентам есть: https://t.me/onec_addin. Возможно помогут. Или предложат на rust переписать 😄

**Comment by TimurDD** [comment]
Спасибо за ответ. На Rust уже предложили переписать)) По итогу вышел на ошибку при вызове метода grpc.
`E1105 05:44:57.304000000 30516 grpc_ares_ev_driver_windows.cc:311] ASSERTION FAILED: *from_len <= recv_from_source_addr_len_`
Буду копать дальше)
